sudo: true
env: 
  CXX=g++-4.8 
  ANDROID_HOME=/home/travis/build/CMPT371Team1/Project/android-sdk-linux
  PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/25.0.1:/usr/lib/google-cloud-sdk/platform/google_appengine
  PATH=/home/travis/build/CMPT371Team1/Project/geckodriver:${PATH}
  PATH/home/travis/.nvm/versions/node/v6.9.4/lib/node_modules/jasmine/bin:${PATH}
  PYTHONPATH=${PYTHONPATH}:/usr/lib/google-cloud-sdk/platform/google_appengine
  PYTHONPATH=${PYTHONPATH}:${TRAVIS_HOME}
  BUILD_TYPE=test


branches:
  only:
  - master
  - develop
  - build_dev
  - id4
    
language: node_js
cache:
  directories:
    - /home/travis/.nvm/
node_js:
- 6.9.4

matrix:
  include:
  - os: android
  - os: osx
    osx_image: xcode7 

addons:
  firefox: "47.0.1"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - oracle-java8-installer
    - lib32stdc++6
    #- lib32z1
    

  
install:
  - "./scripts/install.sh"
  - echo $TRAVIS_OS_NAME

before_script:
  - "./scripts/before_script.sh"

script:
  - "./scripts/build_script.sh"
  
after_success:
  - "./scripts/systeminfo_script.sh"
  - "./scripts/stage_script.sh"
  
after_failure:
  - "./scripts/systeminfo_script.sh"
  
deploy:
 provider: script
 script: "scripts/deploy_script.sh"
 skip_cleanup: true
 on:
   branch: develop  


notifications:
  email: false
  slack:
    secure: eJICeB2vgmD0n18MKS725pSaCXJgB3dCzh7Nd/1fPh67Hs+n8UzzeurpkKbenrwlZLJPEGBTPy1N2yJGwL4wD4xA/MJVrxXAop351LEa8eRZiGt4za6LLZBraXCSUy/CGAUja+x72yEBq6Ua3b5F9q+d5xJ+cYnSAK2Hw2M2HswW7lhVil9i/HfJAfC4CqC63ByYB0N+mNQ/vdoWv4z7TJds30wVw49Fk0WKNyMfzyhd0whS3FtmKW4JYAfjz5eOjBC7dOuYZNAd7zDXrgn/w8Dff9pU5KhfOHRPwMYW1ThIgKH/qey3MbUBFMvizXSvvqcHZKxahTDDxTg66SHtzaY/uFjiIb6CbFXY18HneLxqzIdU2DPBHfx96+mkQNxX2QCrH4n11VWiyMnh0JVYh4/muGiA+z2lj7Hx1iz6vALuCObWV/ZBTnqv7ysAXK8WDv++9Hn0Vk5vhac86lLsPsXIG8LiwziYWFuFgTB+HfVbVN/8opYDw2GoeurjYE3raJZFpiBYD+ATh+JdnrAcX2hoLuQ++SR8za+QvHmrqyzS9GURmAZYMGZYXT/gcGZTwwKVbBBLxVgCpc6nFsQnnCkgpvsIJhToazqdZJreueyhUu8y6oKYDQBmgqBqw2Hpuh6UmVgU7sYBcMtlBHMug8BTWcbHcJfM9EBSqnUlAOE=
