notifications:
  email: false
  slack:
    secure: eJICeB2vgmD0n18MKS725pSaCXJgB3dCzh7Nd/1fPh67Hs+n8UzzeurpkKbenrwlZLJPEGBTPy1N2yJGwL4wD4xA/MJVrxXAop351LEa8eRZiGt4za6LLZBraXCSUy/CGAUja+x72yEBq6Ua3b5F9q+d5xJ+cYnSAK2Hw2M2HswW7lhVil9i/HfJAfC4CqC63ByYB0N+mNQ/vdoWv4z7TJds30wVw49Fk0WKNyMfzyhd0whS3FtmKW4JYAfjz5eOjBC7dOuYZNAd7zDXrgn/w8Dff9pU5KhfOHRPwMYW1ThIgKH/qey3MbUBFMvizXSvvqcHZKxahTDDxTg66SHtzaY/uFjiIb6CbFXY18HneLxqzIdU2DPBHfx96+mkQNxX2QCrH4n11VWiyMnh0JVYh4/muGiA+z2lj7Hx1iz6vALuCObWV/ZBTnqv7ysAXK8WDv++9Hn0Vk5vhac86lLsPsXIG8LiwziYWFuFgTB+HfVbVN/8opYDw2GoeurjYE3raJZFpiBYD+ATh+JdnrAcX2hoLuQ++SR8za+QvHmrqyzS9GURmAZYMGZYXT/gcGZTwwKVbBBLxVgCpc6nFsQnnCkgpvsIJhToazqdZJreueyhUu8y6oKYDQBmgqBqw2Hpuh6UmVgU7sYBcMtlBHMug8BTWcbHcJfM9EBSqnUlAOE=


# build only when these branches are pushed to
branches:
  only:
    - master
    - develop
    
matrix:
  include:
  - os: andriod
    dist: 6.0.0
  - os: osx
    os_image: xCode7

language: node_js
node_js:
  # version we are using
  - "6.9.4"
jdk:
  - oraclejdk8

sudo: true
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - oracle-java8-installer
    - lib32stdc++6
    - lib32z1
env:
  CXX=g++-4.8
  JAVA_HOME=/usr/lib/jvm/java-8-oracle


    
install:
  - chmod -x /scripts/install.sh
  - ./scripts/install.sh

before_script:
  - wget http://dl.google.com/android/android-sdk_r24.3.4-linux.tgz
  - echo $JAVA_HOME
  - tar -xvf android-sdk_r24.3.4-linux.tgz
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-23.0.3
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-24
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-support
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - mkdir www
  - java -version
  - ls /usr/lib/jvm/
  - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2

script:
  # this is voodoo to me
  - ionic platform remove android
  # this isn't
  - ionic platform add android 
  - ionic platform add ios 
  - ionic platform add browser 
  - ionic build
  # commented out since our project doesn't have these files, keeping it around in case we do need it later
  # - ls ionic info
